namespace IpBlockingApi.Common;

/// <summary>
/// Static mapping of ISO 3166-1 alpha-2 country codes to display names.
/// Scoped to 10 countries as per implementation requirements.
/// Used for country-name resolution and validating temporal-block requests.
/// </summary>
public static class CountryNameLookup
{
    /// <summary>
    /// Read-only dictionary of supported country codes (uppercase) → names.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> Countries =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["AF"] = "Afghanistan",
            ["AL"] = "Albania",
            ["DZ"] = "Algeria",
            ["AS"] = "American Samoa",
            ["AD"] = "Andorra",
            ["AO"] = "Angola",
            ["AI"] = "Anguilla",
            ["AQ"] = "Antarctica",
            ["AG"] = "Antigua and Barbuda",
            ["AR"] = "Argentina",
            ["AM"] = "Armenia",
            ["AW"] = "Aruba",
            ["AU"] = "Australia",
            ["AT"] = "Austria",
            ["AZ"] = "Azerbaijan",
            ["BS"] = "Bahamas",
            ["BH"] = "Bahrain",
            ["BD"] = "Bangladesh",
            ["BB"] = "Barbados",
            ["BY"] = "Belarus",
            ["BE"] = "Belgium",
            ["BZ"] = "Belize",
            ["BJ"] = "Benin",
            ["BM"] = "Bermuda",
            ["BT"] = "Bhutan",
            ["BO"] = "Bolivia",
            ["BA"] = "Bosnia and Herzegovina",
            ["BW"] = "Botswana",
            ["BR"] = "Brazil",
            ["IO"] = "British Indian Ocean Territory",
            ["BN"] = "Brunei Darussalam",
            ["BG"] = "Bulgaria",
            ["BF"] = "Burkina Faso",
            ["BI"] = "Burundi",
            ["KH"] = "Cambodia",
            ["CM"] = "Cameroon",
            ["CA"] = "Canada",
            ["CV"] = "Cape Verde",
            ["KY"] = "Cayman Islands",
            ["CF"] = "Central African Republic",
            ["TD"] = "Chad",
            ["CL"] = "Chile",
            ["CN"] = "China",
            ["CX"] = "Christmas Island",
            ["CC"] = "Cocos (Keeling) Islands",
            ["CO"] = "Colombia",
            ["KM"] = "Comoros",
            ["CG"] = "Congo",
            ["CD"] = "Congo (Democratic Republic of the)",
            ["CK"] = "Cook Islands",
            ["CR"] = "Costa Rica",
            ["CI"] = "Côte d'Ivoire",
            ["HR"] = "Croatia",
            ["CU"] = "Cuba",
            ["CW"] = "Curaçao",
            ["CY"] = "Cyprus",
            ["CZ"] = "Czech Republic",
            ["DK"] = "Denmark",
            ["DJ"] = "Djibouti",
            ["DM"] = "Dominica",
            ["DO"] = "Dominican Republic",
            ["EC"] = "Ecuador",
            ["EG"] = "Egypt",
            ["SV"] = "El Salvador",
            ["GQ"] = "Equatorial Guinea",
            ["ER"] = "Eritrea",
            ["EE"] = "Estonia",
            ["ET"] = "Ethiopia",
            ["FK"] = "Falkland Islands (Malvinas)",
            ["FO"] = "Faroe Islands",
            ["FJ"] = "Fiji",
            ["FI"] = "Finland",
            ["FR"] = "France",
            ["GF"] = "French Guiana",
            ["PF"] = "French Polynesia",
            ["TF"] = "French Southern Territories",
            ["GA"] = "Gabon",
            ["GM"] = "Gambia",
            ["GE"] = "Georgia",
            ["DE"] = "Germany",
            ["GH"] = "Ghana",
            ["GI"] = "Gibraltar",
            ["GR"] = "Greece",
            ["GL"] = "Greenland",
            ["GD"] = "Grenada",
            ["GP"] = "Guadeloupe",
            ["GU"] = "Guam",
            ["GT"] = "Guatemala",
            ["GG"] = "Guernsey",
            ["GN"] = "Guinea",
            ["GW"] = "Guinea-Bissau",
            ["GY"] = "Guyana",
            ["HT"] = "Haiti",
            ["HM"] = "Heard Island and McDonald Islands",
            ["HN"] = "Honduras",
            ["HK"] = "Hong Kong",
            ["HU"] = "Hungary",
            ["IS"] = "Iceland",
            ["IN"] = "India",
            ["ID"] = "Indonesia",
            ["IR"] = "Iran",
            ["IQ"] = "Iraq",
            ["IE"] = "Ireland",
            ["IL"] = "Israel",
            ["IT"] = "Italy",
            ["JM"] = "Jamaica",
            ["JP"] = "Japan",
            ["JE"] = "Jersey",
            ["JO"] = "Jordan",
            ["KZ"] = "Kazakhstan",
            ["KE"] = "Kenya",
            ["KI"] = "Kiribati",
            ["KW"] = "Kuwait",
            ["KG"] = "Kyrgyzstan",
            ["LA"] = "Lao People's Democratic Republic",
            ["LV"] = "Latvia",
            ["LB"] = "Lebanon",
            ["LS"] = "Lesotho",
            ["LR"] = "Liberia",
            ["LY"] = "Libya",
            ["LI"] = "Liechtenstein",
            ["LT"] = "Lithuania",
            ["LU"] = "Luxembourg",
            ["MO"] = "Macao",
            ["MK"] = "North Macedonia",
            ["MG"] = "Madagascar",
            ["MW"] = "Malawi",
            ["MY"] = "Malaysia",
            ["MV"] = "Maldives",
            ["ML"] = "Mali",
            ["MT"] = "Malta",
            ["MH"] = "Marshall Islands",
            ["MQ"] = "Martinique",
            ["MR"] = "Mauritania",
            ["MU"] = "Mauritius",
            ["YT"] = "Mayotte",
            ["MX"] = "Mexico",
            ["FM"] = "Micronesia (Federated States of)",
            ["MD"] = "Moldova",
            ["MC"] = "Monaco",
            ["MN"] = "Mongolia",
            ["ME"] = "Montenegro",
            ["MS"] = "Montserrat",
            ["MA"] = "Morocco",
            ["MZ"] = "Mozambique",
            ["MM"] = "Myanmar",
            ["NA"] = "Namibia",
            ["NR"] = "Nauru",
            ["NP"] = "Nepal",
            ["NL"] = "Netherlands",
            ["NC"] = "New Caledonia",
            ["NZ"] = "New Zealand",
            ["NI"] = "Nicaragua",
            ["NE"] = "Niger",
            ["NG"] = "Nigeria",
            ["NU"] = "Niue",
            ["NF"] = "Norfolk Island",
            ["KP"] = "North Korea",
            ["MP"] = "Northern Mariana Islands",
            ["NO"] = "Norway",
            ["OM"] = "Oman",
            ["PK"] = "Pakistan",
            ["PW"] = "Palau",
            ["PS"] = "Palestine",
            ["PA"] = "Panama",
            ["PG"] = "Papua New Guinea",
            ["PY"] = "Paraguay",
            ["PE"] = "Peru",
            ["PH"] = "Philippines",
            ["PN"] = "Pitcairn",
            ["PL"] = "Poland",
            ["PT"] = "Portugal",
            ["PR"] = "Puerto Rico",
            ["QA"] = "Qatar",
            ["RO"] = "Romania",
            ["RU"] = "Russia",
            ["RW"] = "Rwanda",
            ["RE"] = "Réunion",
            ["BL"] = "Saint Barthélemy",
            ["SH"] = "Saint Helena, Ascension and Tristan da Cunha",
            ["KN"] = "Saint Kitts and Nevis",
            ["LC"] = "Saint Lucia",
            ["MF"] = "Saint Martin",
            ["SX"] = "Sint Maarten",
            ["ST"] = "São Tomé and Príncipe",
            ["SA"] = "Saudi Arabia",
            ["SN"] = "Senegal",
            ["RS"] = "Serbia",
            ["SC"] = "Seychelles",
            ["SL"] = "Sierra Leone",
            ["SG"] = "Singapore",
            ["SK"] = "Slovakia",
            ["SI"] = "Slovenia",
            ["SB"] = "Solomon Islands",
            ["SO"] = "Somalia",
            ["ZA"] = "South Africa",
            ["GS"] = "South Georgia and the South Sandwich Islands",
            ["KR"] = "South Korea",
            ["SS"] = "South Sudan",
            ["ES"] = "Spain",
            ["LK"] = "Sri Lanka",
            ["SD"] = "Sudan",
            ["SR"] = "Suriname",
            ["SJ"] = "Svalbard and Jan Mayen",
            ["SE"] = "Sweden",
            ["CH"] = "Switzerland",
            ["SY"] = "Syrian Arab Republic",
            ["TW"] = "Taiwan",
            ["TJ"] = "Tajikistan",
            ["TZ"] = "Tanzania",
            ["TH"] = "Thailand",
            ["TL"] = "Timor-Leste",
            ["TG"] = "Togo",
            ["TK"] = "Tokelau",
            ["TO"] = "Tonga",
            ["TT"] = "Trinidad and Tobago",
            ["TN"] = "Tunisia",
            ["TR"] = "Turkey",
            ["TM"] = "Turkmenistan",
            ["TC"] = "Turks and Caicos Islands",
            ["TV"] = "Tuvalu",
            ["UG"] = "Uganda",
            ["UA"] = "Ukraine",
            ["AE"] = "United Arab Emirates",
            ["GB"] = "United Kingdom",
            ["US"] = "United States",
            ["UY"] = "Uruguay",
            ["UZ"] = "Uzbekistan",
            ["VU"] = "Vanuatu",
            ["VA"] = "Vatican City",
            ["VE"] = "Venezuela",
            ["VN"] = "Vietnam",
            ["WF"] = "Wallis and Futuna",
            ["EH"] = "Western Sahara",
            ["YE"] = "Yemen",
            ["ZM"] = "Zambia",
            ["ZW"] = "Zimbabwe"
        };

    /// <summary>
    /// Returns the display name for <paramref name="code"/>, or the uppercased code
    /// itself when the code is not in the known list.
    /// </summary>
    public static string GetName(string code)
        => Countries.TryGetValue(code.ToUpperInvariant(), out var name)
            ? name
            : code.ToUpperInvariant();

    /// <summary>
    /// Returns <c>true</c> when <paramref name="code"/> is present in the known list.
    /// Used to validate temporal block requests.
    /// </summary>
    public static bool IsKnownCode(string code)
        => Countries.ContainsKey(code.ToUpperInvariant());
}